title: Avrami.Me
author: Avrami Hammer
#avatar_url: https://assets.avrami.me/profile.png
email: queries@avrami.me
description: Avrami's Blog, Baked using love, jekyll, and github.

google_analytics: UA-131741134-1

collections:
  posts:
    title: Blog

  projects:
    title: Projects

    output: true
    advertise: true
    order: 4

  work:
    output: true
    advertise: true
    order: 1

    title: Work Experience

  volunteering:
    output: true
    advertise: true
    order: 3

    title: Volunteer Experience
  education:
    output: true
    advertise: true
    order: 2

    title: Education


paginate: 5

github_username:  Hammer-Inc
linkedin_username: avrami-hammer

portfolio:
  headline: Skilled Software Engineer, specializing in deploying reliable Web Apps at Scale

skills:
  - name: Python
    confidence: 100
  - name: SQL
    confidence: 80
  - name: JavaScript
    confidence: 90
  - name: Docker
    confidence: 90
  - name: Web Development
    confidence: 100
  - name: Machine Learning
    confidence: 50

google_analytics: UA-131741134-1
plugins:
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: true