title: Avrami.Me
author: Avrami Hammer
#avatar_url: https://assets.avrami.me/profile.png
email: queries@avrami.me
description: Avrami's Blog, Baked using love, jekyll, and github.

google_analytics: UA-131741134-1

collections:
  projects:
    output: true
  work:
    output: true
  volunteer:
    output: true


paginate: 5

github_username:  Hammer-Inc
linkedin_username: avrami-hammer

portfolio:
  headline: Extremely Competent Software Engineer, specializing in deploying reliable Web Apps at Scale

skills:
  - name: Python
    confidence: 100
  - name: SQL
    confidence: 80
  - name: JavaScript
    confidence: 90
  - name: Docker
    confidence: 90
  - name: Web Development
    confidence: 100

google_analytics: UA-131741134-1
plugins:
  - jekyll-feed
  - jekyll-sitemap